{{with .Values -}}
---
###
### Grafana
###
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-grafana-config
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: grafana
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
data:
  grafana.ini: |-
    instance_name = linkerd-grafana

    [server]
    root_url = %(protocol)s://%(domain)s:/grafana/

    [auth]
    disable_login_form = true

    [auth.anonymous]
    enabled = true
    org_role = Editor

    [auth.basic]
    enabled = false

    [analytics]
    check_for_updates = false

    [panels]
    disable_sanitize_html = true

  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://linkerd-prometheus.{{.global.Namespace}}.svc.{{.global.ClusterDomain}}:9090
      isDefault: true
      jsonData:
        timeInterval: "5s"
      version: 1
      editable: true

  dashboards.yaml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards
        homeDashboardId: linkerd-top-line
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-grafana
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: grafana
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.global.ControllerComponentLabel}}: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
---
{{ $_ := set .global.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .global.Proxy "Component" "linkerd-grafana" -}}
{{ include "linkerd.proxy.validation" .global.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
  labels:
    {{.global.ControllerComponentLabel}}: grafana
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  name: linkerd-grafana
  namespace: {{.global.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{.global.ControllerComponentLabel}}: grafana
      {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
      {{- include "partials.proxy.labels" .global.Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .global.Proxy| nindent 8}}
      labels:
        {{.global.ControllerComponentLabel}}: grafana
        {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
        {{- include "partials.proxy.labels" .global.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      containers:
      - env:
        - name: GF_PATHS_DATA
          value: /data
        image: {{.GrafanaImage}}:{{default .global.LinkerdVersion .ControllerImageVersion}}
        imagePullPolicy: {{.global.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
        {{- if .GrafanaResources -}}
        {{- include "partials.resources" .GrafanaResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: 472
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/grafana
          name: grafana-config
          readOnly: true
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-grafana
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          items:
          - key: grafana.ini
            path: grafana.ini
          - key: datasources.yaml
            path: provisioning/datasources/datasources.yaml
          - key: dashboards.yaml
            path: provisioning/dashboards/dashboards.yaml
          name: linkerd-grafana-config
        name: grafana-config
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
{{end -}}
