{{with .Values -}}
---
###
### Grafana RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-grafana
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: grafana
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
{{- end }}
