{{ with .Values -}}
{{ if not .DisableHeartBeat -}}
---
###
### Heartbeat
###
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linkerd-heartbeat
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: heartbeat
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  schedule: "{{.HeartbeatSchedule}}"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{.global.ControllerComponentLabel}}: heartbeat
          annotations:
            {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        spec:
          {{- include "linkerd.node-selector" . | nindent 10 }}
          serviceAccountName: linkerd-heartbeat
          restartPolicy: Never
          containers:
          - name: heartbeat
            image: {{.ControllerImage}}:{{default .global.LinkerdVersion .ControllerImageVersion}}
            imagePullPolicy: {{.global.ImagePullPolicy}}
            args:
            - "heartbeat"
            - "-prometheus-url=http://linkerd-prometheus.{{.global.Namespace}}.svc.{{.global.ClusterDomain}}:9090"
            - "-controller-namespace={{.global.Namespace}}"
            - "-log-level={{.ControllerLogLevel}}"
            {{- if .HeartbeatResources -}}
            {{- include "partials.resources" .HeartbeatResources | nindent 12 }}
            {{- end }}
            securityContext:
              runAsUser: {{.ControllerUID}}
{{- end }}
{{- end }}
