{{with .Values -}}
{{if .global.Identity -}}
---
###
### Identity Controller Service
###
{{ if and (.global.Identity.Issuer) (eq .global.Identity.Issuer.Scheme "linkerd.io/tls") -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-identity-issuer
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: identity
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
    {{- if .global.Identity.Issuer.CrtExpiryAnnotation}}
    {{.global.Identity.Issuer.CrtExpiryAnnotation}}: {{required "Please provide the identity issuer certificate expiry date" .global.Identity.Issuer.CrtExpiry}}
    {{- end}}
data:
  crt.pem: {{b64enc (required "Please provide the identity issuer certificate" .global.Identity.Issuer.TLS.CrtPEM | trim)}}
  key.pem: {{b64enc (required "Please provide the identity issue private key" .global.Identity.Issuer.TLS.KeyPEM | trim)}}
{{- end}}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-identity
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: identity
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.global.ControllerComponentLabel}}: identity
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
{{ $_ := set .global.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .global.Proxy "Component" "linkerd-identity" -}}
{{ include "linkerd.proxy.validation" .global.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
  labels:
    {{.global.ControllerComponentLabel}}: identity
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  name: linkerd-identity
  namespace: {{.global.Namespace}}
spec:
  replicas: {{.ControllerReplicas}}
  selector:
    matchLabels:
      {{.global.ControllerComponentLabel}}: identity
      {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
      {{- include "partials.proxy.labels" .global.Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .global.Proxy| nindent 8}}
      labels:
        {{.global.ControllerComponentLabel}}: identity
        {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
        {{- include "partials.proxy.labels" .global.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .EnablePodAntiAffinity -}}
      {{- $local := dict "Component" "identity" "Label" .global.ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - identity
        - -log-level={{.ControllerLogLevel}}
        {{- include "partials.linkerd.trace" . | nindent 8 -}}
        image: {{.ControllerImage}}:{{default .global.LinkerdVersion .ControllerImageVersion}}
        imagePullPolicy: {{.global.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9990
          initialDelaySeconds: 10
        name: identity
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 9990
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9990
        {{- if .global.IdentityResources -}}
        {{- include "partials.resources" .global.IdentityResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
        - mountPath: /var/run/linkerd/identity/issuer
          name: identity-issuer
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-identity
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - name: identity-issuer
        secret:
          secretName: linkerd-identity-issuer
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
{{end -}}
{{end -}}
