---
###
### linkerd values
###
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-values
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: controller
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  values: |-
    global:
      {{- toYaml .Values.global | trim | nindent 6}}
    grafana:
      {{- toYaml .Values.grafana | trim | nindent 6}}
    prometheus:
      {{- toYaml .Values.prometheus | trim | nindent 6}}

