{{- /*
  This config-map is used to store the configuration of add-ons, which is useful during upgrades.

  Note: Grafana add-on is enabled by default
*/ -}}
---
###
### linkerd values
###
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config-addons
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  values: |-
    global:
      grafanaUrl: {{.Values.global.grafanaUrl}}
    grafana:
      {{- include "linkerd.addons.sanitize-config" .Values.grafana}}
    tracing:
      {{- include "linkerd.addons.sanitize-config" .Values.tracing}}
