{{ if .Values.installValuesConfig -}}
{{- $dupValues := .Values -}}
{{- $dupValues := omit $dupValues "partials" -}}
{{- range $key, $value := $dupValues -}}
  {{- if kindIs "map" $value -}}
    {{- if hasKey $value "global" -}}
      {{- $dupValues := set $dupValues $key (unset $value "global") -}}
    {{- end -}}
    {{- if hasKey $value "partials" -}}
      {{- $dupValues := set $dupValues $key (unset $value "partials") -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
---
###
### linkerd values
###
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-values
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: controller
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  values: |-
    tracing:
  {{- toYaml $dupValues.tracing | trim | nindent 6}}
{{ end }}