{{with .Values -}}
---
###
### Proxy Injector
###
---
{{ $_ := set .global.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .global.Proxy "Component" "linkerd-proxy-injector" -}}
{{ include "linkerd.proxy.validation" .global.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
  labels:
    {{.global.ControllerComponentLabel}}: proxy-injector
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  name: linkerd-proxy-injector
  namespace: {{.global.Namespace}}
spec:
  replicas: {{.ControllerReplicas}}
  selector:
    matchLabels:
      {{.global.ControllerComponentLabel}}: proxy-injector
  template:
    metadata:
      annotations:
        {{- if empty .CliVersion }}
        linkerd.io/helm-release-version: {{ $.Release.Revision | quote}}
        {{- end }}
        {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .global.Proxy| nindent 8}}
      labels:
        {{.global.ControllerComponentLabel}}: proxy-injector
        {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
        {{- include "partials.proxy.labels" .global.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .EnablePodAntiAffinity -}}
      {{- $local := dict "Component" "proxy-injector" "Label" .global.ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - proxy-injector
        - -log-level={{.ControllerLogLevel}}
        image: {{.ControllerImage}}:{{default .global.LinkerdVersion .ControllerImageVersion}}
        imagePullPolicy: {{.global.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9995
          initialDelaySeconds: 10
        name: proxy-injector
        ports:
        - containerPort: 8443
          name: proxy-injector
        - containerPort: 9995
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9995
        {{- if .ProxyInjectorResources -}}
        {{- include "partials.resources" .ProxyInjectorResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
        - mountPath: /var/run/linkerd/tls
          name: tls
          readOnly: true
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-proxy-injector
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - name: tls
        secret:
          secretName: linkerd-proxy-injector-tls
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-proxy-injector
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: proxy-injector
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.global.ControllerComponentLabel}}: proxy-injector
  ports:
  - name: proxy-injector
    port: 443
    targetPort: proxy-injector
{{ end -}}
