{{with .Values -}}
---
###
### Control Plane PSP
###
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: linkerd-{{.global.Namespace}}-control-plane
  labels:
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
spec:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  {{- if empty .NoInitContainer }}
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
  {{- end}}
  requiredDropCapabilities:
  - ALL
  hostNetwork: false
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  runAsUser:
    {{- if .NoInitContainer }}
    rule: MustRunAsNonRoot
    {{- else }}
    rule: RunAsAny
    {{- end }}
  supplementalGroups:
    rule: MustRunAs
    ranges:
    {{- if .NoInitContainer }}
    - min: 10001
      max: 65535
    {{- else }}
    - min: 1
      max: 65535
    {{- end }}
  fsGroup:
    rule: MustRunAs
    ranges:
    {{- if .NoInitContainer }}
    - min: 10001
      max: 65535
    {{- else }}
    - min: 1
      max: 65535
    {{- end }}
  volumes:
  - configMap
  - emptyDir
  - secret
  - projected
  - downwardAPI
  - persistentVolumeClaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-psp
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
rules:
- apiGroups: ['policy', 'extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - linkerd-{{.global.Namespace}}-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-psp
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
roleRef:
  kind: Role
  name: linkerd-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-controller
  namespace: {{.global.Namespace}}
- kind: ServiceAccount
  name: linkerd-destination
  namespace: {{.global.Namespace}}
- kind: ServiceAccount
  name: linkerd-grafana
  namespace: {{.global.Namespace}}
{{ if not .DisableHeartBeat -}}
- kind: ServiceAccount
  name: linkerd-heartbeat
  namespace: {{.global.Namespace}}
{{ end -}}
- kind: ServiceAccount
  name: linkerd-identity
  namespace: {{.global.Namespace}}
- kind: ServiceAccount
  name: linkerd-prometheus
  namespace: {{.global.Namespace}}
- kind: ServiceAccount
  name: linkerd-proxy-injector
  namespace: {{.global.Namespace}}
- kind: ServiceAccount
  name: linkerd-sp-validator
  namespace: {{.global.Namespace}}
- kind: ServiceAccount
  name: linkerd-tap
  namespace: {{.global.Namespace}}
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.global.Namespace}}
{{ end -}}
