{{with .Values -}}
---
###
### Tap RBAC
###
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.global.Namespace}}-tap
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "replicationcontrollers", "namespaces", "nodes"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["extensions", "batch"]
  resources: ["jobs"]
  verbs: ["list" , "get", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.global.Namespace}}-tap-admin
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
rules:
- apiGroups: ["tap.linkerd.io"]
  resources: ["*"]
  verbs: ["watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.global.Namespace}}-tap
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-{{.global.Namespace}}-tap
subjects:
- kind: ServiceAccount
  name: linkerd-tap
  namespace: {{.global.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-{{.global.Namespace}}-tap-auth-delegator
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: linkerd-tap
  namespace: {{.global.Namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-tap
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-{{.global.Namespace}}-tap-auth-reader
  namespace: kube-system
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: linkerd-tap
  namespace: {{.global.Namespace}}
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-tap-tls
  namespace: {{ .global.Namespace }}
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
type: Opaque
data:
  {{ $ca := genCA (printf "linkerd-tap.%s.svc" .global.Namespace) 365 -}}
  crt.pem: {{ ternary (b64enc $ca.Cert) (b64enc (trim .Tap.CrtPEM)) (empty .Tap.CrtPEM) }}
  key.pem: {{ ternary (b64enc $ca.Key) (b64enc (trim .Tap.KeyPEM)) (empty .Tap.KeyPEM) }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.tap.linkerd.io
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
spec:
  group: tap.linkerd.io
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: linkerd-tap
    namespace: {{.global.Namespace}}
  caBundle: {{ ternary (b64enc $ca.Cert) (b64enc (trim .Tap.CrtPEM)) (empty .Tap.CrtPEM) }}
{{end -}}
