{{with .Values -}}
---
###
### Tap
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-tap
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.global.ControllerComponentLabel}}: tap
  ports:
  - name: grpc
    port: 8088
    targetPort: 8088
  - name: apiserver
    port: 443
    targetPort: apiserver
---
{{ $_ := set .global.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .global.Proxy "Component" "linkerd-tap" -}}
{{ include "linkerd.proxy.validation" .global.Proxy -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
  labels:
    {{.global.ControllerComponentLabel}}: tap
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  name: linkerd-tap
  namespace: {{.global.Namespace}}
spec:
  replicas: {{.ControllerReplicas}}
  selector:
    matchLabels:
      {{.global.ControllerComponentLabel}}: tap
      {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
      {{- include "partials.proxy.labels" .global.Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{- if empty .CliVersion }}
        linkerd.io/helm-release-version: {{ $.Release.Revision | quote}}
        {{- end }}
        {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .global.Proxy| nindent 8}}
      labels:
        {{.global.ControllerComponentLabel}}: tap
        {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
        {{- include "partials.proxy.labels" .global.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .EnablePodAntiAffinity -}}
      {{- $local := dict "Component" "tap" "Label" .global.ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - tap
        - -controller-namespace={{.global.Namespace}}
        - -log-level={{.ControllerLogLevel}}
        {{- include "partials.linkerd.trace" . | nindent 8 -}}
        image: {{.ControllerImage}}:{{default .global.LinkerdVersion .ControllerImageVersion}}
        imagePullPolicy: {{.global.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9998
          initialDelaySeconds: 10
        name: tap
        ports:
        - containerPort: 8088
          name: grpc
        - containerPort: 8089
          name: apiserver
        - containerPort: 9998
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9998
        {{- if .TapResources -}}
        {{- include "partials.resources" .TapResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/tls
          name: tls
          readOnly: true
        - mountPath: /var/run/linkerd/config
          name: config
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-tap
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
      - name: tls
        secret:
          secretName: linkerd-tap-tls
{{ end -}}
