{{with .Values -}}
---
###
### Web
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: web
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.global.ControllerComponentLabel}}: web
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: admin-http
    port: 9994
    targetPort: 9994
---
{{ $_ := set .global.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .global.Proxy "Component" "linkerd-web" -}}
{{ include "linkerd.proxy.validation" .global.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
  labels:
    {{.global.ControllerComponentLabel}}: web
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  name: linkerd-web
  namespace: {{.global.Namespace}}
spec:
  replicas: {{.Dashboard.Replicas}}
  selector:
    matchLabels:
      {{.global.ControllerComponentLabel}}: web
      {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
      {{- include "partials.proxy.labels" .global.Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .global.Proxy| nindent 8}}
      labels:
        {{.global.ControllerComponentLabel}}: web
        {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
        {{- include "partials.proxy.labels" .global.Proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      containers:
      - args:
        - -api-addr=linkerd-controller-api.{{.global.Namespace}}.svc.{{.global.ClusterDomain}}:8085
        - -grafana-addr=linkerd-grafana.{{.global.Namespace}}.svc.{{.global.lusterDomain}}:3000
        - -controller-namespace={{.global.Namespace}}
        - -log-level={{.ControllerLogLevel}}
        {{- $hostFull := replace "." "\\." (printf "linkerd-web.%s.svc.%s" .global.Namespace .global.ClusterDomain) }}
        {{- $hostAbbrev := replace "." "\\." (printf "linkerd-web.%s.svc" .global.Namespace) }}
        - -enforced-host=^(localhost|127\.0\.0\.1|{{ $hostFull }}|{{ $hostAbbrev }}|\[::1\])(:\d+)?$
        {{- include "partials.linkerd.trace" . | nindent 8 -}}
        image: {{.WebImage}}:{{default .global.LinkerdVersion .ControllerImageVersion}}
        imagePullPolicy: {{.global.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9994
          initialDelaySeconds: 10
        name: web
        ports:
        - containerPort: 8084
          name: http
        - containerPort: 9994
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9994
        {{- if .WebResources -}}
        {{- include "partials.resources" .WebResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-web
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
{{end -}}
