{{with .Values -}}
---
###
### Tracing Collector Service
###
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-collector-conf
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: linkerd-collector
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
data:
  linkerd-collector-config: |
    receivers:
      opencensus:
        port: 55678
      zipkin:
        port: 9411
    queued-exporters:
      jaeger-all-in-one:
        num-workers: 4
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: http://linkerd-jaeger.linkerd:14268/api/traces
          timeout: 5s
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-collector
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: linkerd-collector
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  ports:
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    {{.global.ControllerComponentLabel}}: linkerd-collector
---
{{ $_ := set .global.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .global.Proxy "Component" "linkerd-collector" -}}
{{ include "linkerd.proxy.validation" .global.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: linkerd-collector
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: linkerd-collector
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      {{.global.ControllerComponentLabel}}: linkerd-collector
      {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
      {{- include "partials.proxy.labels" .global.Proxy | nindent 6}}
  strategy: {}
  template:
    metadata:
      annotations:
        {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .global.Proxy| nindent 8}}
      labels:
        {{.global.ControllerComponentLabel}}: linkerd-collector
        {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
        {{- include "partials.proxy.labels" .global.Proxy | nindent 8}}
    spec:
      containers:
      - command:
        - /occollector_linux
        - --config=/conf/linkerd-collector-config.yaml
        env:
        - name: GOGC
          value: "80"
        image: omnition/opencensus-collector:0.1.10
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        name: linkerd-collector
        ports:
        - containerPort: 55678
        - containerPort: 9411
        readinessProbe:
          httpGet:
            path: /
            port: 13133
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        volumeMounts:
        - mountPath: /conf
          name: linkerd-collector-config-vol
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-collector
      volumes:
      - configMap:
          items:
          - key: linkerd-collector-config
            path: linkerd-collector-config.yaml
          name: linkerd-collector-conf
        name: linkerd-collector-config-vol
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
status: {}
---
{{ $_ := set .global.Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .global.Proxy "Component" "linkerd-jaeger" -}}
{{ include "linkerd.proxy.validation" .global.Proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-jaeger
  namespace: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
  labels:
    {{.global.ControllerComponentLabel}}: linkerd-jaeger
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{.global.ControllerComponentLabel}}: linkerd-jaeger
      {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
      {{- include "partials.proxy.labels" .global.Proxy | nindent 6}}
  strategy: {}
  template:
    metadata:
      annotations:
        {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
        {{- include "partials.proxy.annotations" .global.Proxy| nindent 8}}
      labels:
        {{.global.ControllerComponentLabel}}: linkerd-jaeger
        {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
        {{- include "partials.proxy.labels" .global.Proxy | nindent 8}}
    spec:
      serviceAccountName: linkerd-jaeger
      dnsPolicy: ClusterFirst
      containers:
      - image: jaegertracing/all-in-one:1.8
        name: jaeger
        ports:
        - containerPort: 14268
          name: collection
        - containerPort: 16686
          name: ui
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .NoInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      volumes:
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-jaeger
  namespace: {{.global.Namespace}}
  labels:
    {{.global.ControllerComponentLabel}}: linkerd-jaeger
    {{.global.ControllerNamespaceLabel}}: {{.global.Namespace}}
  annotations:
    {{.global.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" .global.LinkerdVersion) .CliVersion}}
spec:
  selector:
    {{.global.ControllerComponentLabel}}: linkerd-jaeger
  ports:
  - name: collection
    port: 14268
  - name: ui
    port: 16686
---
{{end -}}